### ISSUE TITLE
Fails to launch

### ISSUE THREAD

**Issue by gazzmanzx6** [SLaweck/homebridge-tuya-smartlamp#4]
I've just updated to version 0.5.1 and Homebridge now fails to launch.
I get the following error:
`[9/7/2019, 12:03:44 PM] Error: ENOENT: no such file or directory, open '/home/pi/.homebridge/history_4000725484f3eb2eb793.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at TuyaOutlet.readTotalConsumption (/home/pi/.npm-global/lib/node_modules/homebridge-tuya-smartlamp/lib/TuyaOutlet.js:131:25)
    at TuyaOutlet.getDeviceService (/home/pi/.npm-global/lib/node_modules/homebridge-tuya-smartlamp/lib/TuyaOutlet.js:64:59)
    at TuyaSmartDevice.getServices (/home/pi/.npm-global/lib/node_modules/homebridge-tuya-smartlamp/index.js:73:79)
    at Server._createAccessory (/home/pi/.npm-global/lib/node_modules/homebridge/lib/server.js:427:36)
    at Server._loadAccessories (/home/pi/.npm-global/lib/node_modules/homebridge/lib/server.js:309:26)
    at Server.run (/home/pi/.npm-global/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/home/pi/.npm-global/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/home/pi/.npm-global/lib/node_modules/homebridge/bin/homebridge:17:22)`

Any ideas what is causing this?

**Comment by SLaweck** [comment]
Version 0.5.2 should fix this.

**Comment by gazzmanzx6** [comment]
Thanks.
Homebridge launches now but it is unable to connect to the socket properly.
The socket has the new firmware in it so I think this might be the problem.
Should this work with the new firmware?

`TuyaResolver device found: { id: '4000725484f3eb2eb793', ip: '192.168.2.33' } +3s
  TuyaAccessory [Fairy lights] resolver answer: { id: '4000725484f3eb2eb793', ip: '192.168.2.33' } +3s
[9/7/2019, 4:27:11 PM] [Fairy lights] [TO] IP address resolved 192.168.2.33
  TuyAPI Connecting to 192.168.2.33... +13ms
  TuyAPI Socket connected. +14ms
  TuyaAccessory [Fairy lights] Device onConneted: connected = true +22ms
  TuyAPI GET Payload: +3ms
  TuyAPI { gwId: '4000725484f3eb2eb793', devId: '4000725484f3eb2eb793' } +1ms
  TuyAPI Error event from socket. 192.168.2.33 { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' } +19ms
  TuyaAccessory [Fairy lights] Device onError: Error: Error from socket
    at Socket.client.on.err (/home/pi/.npm-global/lib/node_modules/homebridge-tuya-smartlamp/node_modules/tuyapi/index.js:323:30)
    at Socket.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:613:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:790:10) +24ms
  TuyAPI Socket closed: 192.168.2.33 +7ms
  TuyaAccessory [Fairy lights] Device onDisconneted: connected = false +5ms
  TuyaAccessory [Fairy lights] ERROR: getSchema timeout - no answer from device within 5000 ms +2s
  TuyaAccessory [Fairy lights] ERROR: getting on/off status error  timeout error +1m`

**Comment by SLaweck** [comment]
I realized that I missed TuyAPI version option.
Please, update to newest version and add:
"version": 3.3
to your config.
Then let me know will that help.

**Comment by gazzmanzx6** [comment]
I've updated to newest version and added version 3.3 but the socket still doesn't respond.
There seem to be some strange characters in the debug text.
`TuyaAccessory [Fairy lights] Device onConneted: connected = true +40ms
  TuyAPI GET Payload: +2ms
  TuyAPI { gwId: '4000725484f3eb2eb793', devId: '4000725484f3eb2eb793' } +0ms
  TuyAPI Received data: 000055aa000000020000000a0000002c00000001d3b65cc380ffabb895616c6c90ba5399d0f15db9053b6db4ddb942aaa9f44d4c0a6830ee0000aa55 +58ms
  TuyAPI Parsed: +5ms
  TuyAPI { payload: 'Ӷ\\À����all��S���]�\u0005;m�ݹB���ML',
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 2 } +0ms
[9/8/2019, 10:20:25 AM] [Fairy lights] [TO] Device connected
  TuyAPI GET Payload: +8ms
  TuyAPI { gwId: '4000725484f3eb2eb793', devId: '4000725484f3eb2eb793' } +0ms
  TuyAPI Received data: 000055aa000000030000000a0000002c00000001d3b65cc380ffabb895616c6c90ba5399d0f15db9053b6db4ddb942aaa9f44d4ca9fe18a20000aa55 +26ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: 'Ӷ\\À����all��S���]�\u0005;m�ݹB���ML',
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 3 } +1ms
  TuyaAccessory [Fairy lights] getSchema => Ӷ\À����all��S���]�;m�ݹB���ML +101ms
  TuyaAccessory [Fairy lights] ERROR: Problem with getted schema Ӷ\À����all��S���]�;m�ݹB���ML +1ms
  TuyaAccessory [Fairy lights] ERROR: getting device in use status error schema problem +0ms
  TuyaAccessory [Fairy lights] ERROR: update values error schema problem +1ms
  TuyAPI Pinging 192.168.2.33 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +28ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 192.168.2.33 +1ms
  TuyaAccessory [Fairy lights] update characteristics values +15s
  TuyaAccessory [Fairy lights] call getProperties [ 1, 4, 5, 6 ] +1ms
  TuyaAccessory [Fairy lights] call getSchema +1ms
  TuyaAccessory [Fairy lights] call connect  +0ms
  TuyAPI GET Payload: +5s
  TuyAPI { gwId: '4000725484f3eb2eb793', devId: '4000725484f3eb2eb793' } +0ms
  TuyAPI Received data: 000055aa000000050000000a0000002c00000001d3b65cc380ffabb895616c6c90ba5399d0f15db9053b6db4ddb942aaa9f44d4cd668e5880000aa55 +63ms
  TuyAPI Parsed: +2ms
  TuyAPI { payload: 'Ӷ\\À����all��S���]�\u0005;m�ݹB���ML',
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 5 } +1ms
  TuyaAccessory [Fairy lights] getSchema => Ӷ\À����all��S���]�;m�ݹB���ML +69ms
  TuyaAccessory [Fairy lights] ERROR: Problem with getted schema Ӷ\À����all��S���]�;m�ݹB���ML +0ms
  TuyaAccessory [Fairy lights] ERROR: getting device in use status error schema problem +1ms`

**Comment by SLaweck** [comment]
Sorry to hear that, I can't help, I don't have any device with protocol version above 3.1 :-(
If you are sure you have right key for device, you should report this in https://github.com/codetheweb/tuyapi.
Cheers
